# -*- coding: utf-8 -*-

from api.constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    ROLE_GLOBAL_ADMIN,
    ROLE_ZONE_ADMIN,
    ROLE_CONSOLE_ADMIN,
    ROLE_NORMAL_USER,
)
from constants import ACTION_V2V_HEALTH_HEALTH_CHECK

API_ACL_V2V_HEALTH = {
    ACTION_V2V_HEALTH_HEALTH_CHECK: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
    }
}
