# -*- coding: utf-8 -*-

from api.constants import (
    CHANNEL_API,
    CHANNEL_SESSION,
    ROLE_GLOBAL_ADMIN,
    ROLE_ZONE_ADMIN,
    ROLE_CONSOLE_ADMIN,
    ROLE_NORMAL_USER,
)
from constants import (
    ACTION_V2V_SRC_PLATFORM_CHECK_SRC_PLATFORM_CONNECTIVITY,
    ACTION_V2V_SRC_PLATFORM_ADD_SRC_PLATFORM,
    ACTION_V2V_SRC_PLATFORM_UPDATE_SRC_PLATFORM,
    ACTION_V2V_SRC_PLATFORM_DELETE_SRC_PLATFORM,
    ACTION_V2V_SRC_PLATFORM_DESCRIBE_SRC_PLATFORM,
    ACTION_V2V_SRC_PLATFORM_DESCRIBE_SRC_PLATFORM_VM
)

API_ACL_V2V_SRC_PLATFORM = {
    ACTION_V2V_SRC_PLATFORM_CHECK_SRC_PLATFORM_CONNECTIVITY: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
    },
    ACTION_V2V_SRC_PLATFORM_ADD_SRC_PLATFORM: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
    },
    ACTION_V2V_SRC_PLATFORM_UPDATE_SRC_PLATFORM: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
    },
    ACTION_V2V_SRC_PLATFORM_DELETE_SRC_PLATFORM: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
    },
    ACTION_V2V_SRC_PLATFORM_DESCRIBE_SRC_PLATFORM: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
    },
    ACTION_V2V_SRC_PLATFORM_DESCRIBE_SRC_PLATFORM_VM: {
        CHANNEL_API: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                      ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
        CHANNEL_SESSION: [ROLE_GLOBAL_ADMIN, ROLE_NORMAL_USER,
                          ROLE_CONSOLE_ADMIN, ROLE_ZONE_ADMIN],
    }
}
