# -*- coding: utf-8 -*-

# 配置
REDIS_CONF_NAME_V2V = "v2v"

# 连接配置
REDIS_SOCKET_TIMEOUT = 5
REDIS_SOCKET_CONNECT_TIMEOUT = 5
REDIS_MAX_CONNECTION_NUMBER = 1000

# key相关定义
REDIS_KEY_PREFIX = "v2v_"
REDIS_KEY_SUFFIX_AUTO_NODE = "auto"
